toc:
  - withData
  - name: Server-Side Rendering (SSR)
    children:
      - getInitialData
      - hydrateData

  - name: Types
    children:
      - GetDataFn
      - ShouldDataUpdateFn
      - MergePropsFn
